name: Cargo Build & Test
on:
  push:
  pull_request:
jobs:
  build_and_test:
    name: Rustmail - latest
    runs-on: ubuntu-22.04
    env:
      SQLX_OFFLINE: true
      CARGO_TERM_COLOR: always
      CARGO_BUILD_JOBS: 3
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4

      - name: Install System Libs
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config build-essential

      - name: Setup Rust
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup target add wasm32-unknown-unknown

      - name: Setup Trunk, Wasm-bindgen & Wasm-opt
        run: |
          wget https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf trunk-x86_64-unknown-linux-gnu.tar.gz
          sudo mv trunk /usr/local/bin/
          rm trunk-x86_64-unknown-linux-gnu.tar.gz

          REQUIRED_VERSION=$(grep -A1 'name = "wasm-bindgen"' Cargo.lock \
            | grep version | head -1 | sed 's/.*version = "\(.*\)"/\1/')
          echo "Required wasm-bindgen version: $REQUIRED_VERSION"
          cargo install wasm-bindgen-cli --version "=$REQUIRED_VERSION" --locked

          wget https://github.com/WebAssembly/binaryen/releases/download/version_128/binaryen-version_128-x86_64-linux.tar.gz
          tar -xzf binaryen-version_128-x86_64-linux.tar.gz
          sudo mv binaryen-version_128/bin/wasm-opt /usr/local/bin/
          rm -rf binaryen-version_128*

          wasm-bindgen --version
          wasm-opt --version

      - name: Build frontend
        working-directory: crates/rustmail_panel
        run: trunk build --release --dist ../rustmail/static --config Trunk.toml

      - name: Build Rust backend
        run: cargo build --verbose -p rustmail

      - name: Run tests
        run: cargo test --verbose -p rustmail